version: 1.0.{build}
branches:
  only:
    - master

skip_tags: true
skip_branch_with_pr: true
shallow_clone: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PYTHON: "C:\\Python34"
      ARCH: "x86"

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PYTHON: "C:\\Python34-x64"
      ARCH: "x64"
    
    - APPVEYOR_BUILD_WORKER_IMAGE: "Ubuntu1804"

build:
  parallel: true
  verbosity: minimal

install:
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - cmd: "powershell Install-Product node 10.13.0 %ARCH%"
  - sh: "nvm install 10.13.0"
  - "npm ci"
  
build_script:
  - "npm run bundle:build"
  - cmd: "%PYTHON%\\Scripts\\pyinstaller.exe --onefile --add-data index.html;. --add-data config;config --add-data public;public --distpath build index.py"
  - cmd: "ren \"build\\index.exe\" lex-win-%ARCH%.exe"
  - sh: "npm run binary:create"

artifacts:
  - path: .\build\*
